### ISSUE TITLE
Crash using Medium Recall Potion while in Nether or Ender

### ISSUE THREAD

**Issue by Traktool** [RobertSkalko/Mine-and-Slash#106]
```
[Server thread/WARN] [net.minecraft.network.NetworkSystem/]: Failed to handle packet for /***.***.***.***:64869
net.minecraft.crash.ReportedException: Ticking player
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:428) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:183) ~[?:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:228) ~[?:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135) [?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) [?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:324) [?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.NullPointerException
	at com.robertx22.mine_and_slash.items.profession.alchemy.single_use.LesserRecallPotionItem.onFinish(LesserRecallPotionItem.java:57) ~[?:1.14.4-2.9.2]
	at com.robertx22.mine_and_slash.items.profession.alchemy.bases.BaseInstantPotion.func_77654_b(BaseInstantPotion.java:76) ~[?:1.14.4-2.9.2]
	at net.minecraft.item.ItemStack.func_77950_b(ItemStack.java:196) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_71036_o(LivingEntity.java:2570) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_71036_o(ServerPlayerEntity.java:981) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_184608_ct(LivingEntity.java:2462) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:1965) ~[?:?]
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:232) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:365) ~[?:?]
	... 8 more
```

**Comment by RobertSkalko** [comment]
should be fixed
