### ISSUE TITLE
Ticking Entitiy Crash

### ISSUE THREAD

**Issue by susan3333333** [RobertSkalko/Mine-and-Slash#173]
Hi, new version has a ticking entity crash, every time in combat in Dungeon, don't know if happens in overworld as I can't get out without a fight LOL:
Using latest Forge, prior version of mine & slash worked fine:

---- Minecraft Crash Report ----
// Why did you do that?

Time: 16/03/20 4:53 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.entity.ai.controller.LookController.func_75651_a(SourceFile:31) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.goal.MeleeAttackGoal.func_75246_d(MeleeAttackGoal.java:98) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.goal.ZombieAttackGoal.func_75246_d(SourceFile:28) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?] {re:classloading}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_201] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_201] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_201] {}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_201] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_201] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_201] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_201] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_201] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_201] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_201] {}
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:80) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:595) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2262) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:462) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.monster.MonsterEntity.func_70636_d(SourceFile:39) ~[?:?] {re:classloading}
	at net.minecraft.entity.monster.ZombieEntity.func_70636_d(ZombieEntity.java:234) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2104) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.monster.ZombieEntity.func_70071_h_(ZombieEntity.java:208) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.World.func_217390_a(World.java:536) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.entity.ai.controller.LookController.func_75651_a(SourceFile:31)
	at net.minecraft.entity.ai.goal.MeleeAttackGoal.func_75246_d(MeleeAttackGoal.java:98)
	at net.minecraft.entity.ai.goal.ZombieAttackGoal.func_75246_d(SourceFile:28)
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:80)
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:595)
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2262)
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:462)
	at net.minecraft.entity.monster.MonsterEntity.func_70636_d(SourceFile:39)
	at net.minecraft.entity.monster.ZombieEntity.func_70636_d(ZombieEntity.java:234)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2104)
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274)
	at net.minecraft.entity.monster.ZombieEntity.func_70071_h_(ZombieEntity.java:208)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600)

-- Entity being ticked --
Details:
	Entity Type: minecraft:husk (net.minecraft.entity.monster.HuskEntity)
	Entity ID: 2036
	Entity Name: Husk
	Entity's Exact location: 511334.51, 55.00, 14657463.81
	Entity's Block location: World: (511334,55,14657463), Chunk: (at 6,3,7 in 31958,916091; contains blocks 511328,0,14657456 to 511343,255,14657471), Region: (998,28627; contains chunks 31936,916064 to 31967,916095, blocks 510976,0,14657024 to 511487,255,14657535)
	Entity's Momentum: 0.00, -0.08, 0.02
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:536)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401)

**Comment by RobertSkalko** [comment]
pushing a fix

**Comment by susan3333333** [comment]
Thanks! New update working fine, like the new dungeons, too. tho I almost went right out into the empty world part, as the rooms are open to the outside, I got shot by a skele and just missed flying out.....also, are the merchants supposed to be nekkid????

**Comment by RobertSkalko** [comment]
Ye, i hurried to make them. Anyway seems solved.

" tho I almost went right out into the empty world part, as the rooms are open to the outside, "

Please send me your log.

**Comment by susan3333333** [comment]
Sorry, I just cleared my test world :(
But I did overview the log first, saw something about player interaction management? mismatch in destroy block pos something or other?
I didn't see anything else interesting that I remember, tho.

**Comment by RobertSkalko** [comment]
Well if it was a tent looking map i fixed that in dev. And no you need to look for something like "structure file missing". If that doesn't happen, then it's a problem with an existing dungeon room being wrongly configured. In that case i'd need you to do /slash dev log dungeon_room and send me that when you stand on the empty room spot. I guess i might need to think of better debugging ways when i have hundreds of dungeon rooms.. Closing as fixed
