### ISSUE TITLE
[1.15.2] Crash while generating new world

### ISSUE THREAD

**Issue by automanic** [RobertSkalko/Mine-and-Slash#258]
I've been working on a modpack for 1.15.2 and it's been going well except this morning when I updated a few mods and altered a couple configs. I started running into problems so I undid a number of the changes and eventually ran into this error. I updated Java, restarted my computer, reinstalled the mod, reinstalled the modpack completely, and even reinstalled Java but nothing worked. The only thing that prevents this error is uninstalling Mine and Slash entirely and completely omitting it. 

This is the error I'm getting:

> Error executing task on Chunk source main thread executor for minecraft:overworld
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58)
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$9825/881491668.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:173)
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213166_h(SourceFile:551)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:135)
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(SourceFile:560)
	at net.minecraft.world.server.ServerChunkProvider.func_217234_d(SourceFile:278)
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:719)
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:151)
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:694)
	at net.minecraft.server.MinecraftServer.func_213186_a(MinecraftServer.java:467)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:109)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:131)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.robertx22.mine_and_slash.saveclasses.Unit.randomizeSuffix(Unit.java:157)
	at com.robertx22.mine_and_slash.saveclasses.Unit.setRandomMobAffixes(Unit.java:140)
	at com.robertx22.mine_and_slash.onevent.entity.OnMobSpawn.Mob(OnMobSpawn.java:138)
	at com.robertx22.mine_and_slash.onevent.entity.OnMobSpawn.setupNewMobOnSpawn(OnMobSpawn.java:87)
	at com.robertx22.mine_and_slash.onevent.entity.OnMobSpawn.onMobSpawn(OnMobSpawn.java:45)
	at net.minecraftforge.eventbus.ASMEventHandler_404_OnMobSpawn_onMobSpawn_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraft.world.server.ServerWorld.func_217440_f(ServerWorld.java:912)
	at net.minecraft.world.server.ChunkManager.lambda$null$25(ChunkManager.java:752)
	at net.minecraft.world.server.ChunkManager$$Lambda$9973/1229968732.apply(Unknown Source)
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162)
	at com.mojang.datafixers.util.Either$$Lambda$9974/1883976346.apply(Unknown Source)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162)
	at net.minecraft.world.server.ChunkManager.lambda$func_219200_b$26(ChunkManager.java:722)
	at net.minecraft.world.server.ChunkManager$$Lambda$9970/747999705.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	... 18 more

Any help with fixing this will be much appreciated!!

**Comment by RobertSkalko** [comment]
Did you delete the mob affixes datapacks? Seems like it failed to generate the affix.
