### ISSUE TITLE
java.lang.NoSuchMethod error on Forge 1.16.5

### ISSUE THREAD

**Issue by gglobensky** [RobertSkalko/Mine-and-Slash#303]
Hi, first off, thanks a whole lot for the port to Forge. 
I have a crash when trying to load the mod (I installed the dependencies).

Here is the trace:
-- Head --
Thread: Render thread
Stacktrace:
	at com.robertx22.age_of_exile.dimension.DungeonDimensionJigsaw.<clinit>(DungeonDimensionJigsaw.java:26) ~[?:?] {re:classloading}
-- MOD mmorpg --
Details:
	Mod File: Mine_and_Slash_BETA-1.16.5-3.0.1.jar
	Failure message: Age Of Exile (mmorpg) has failed to load correctly
		java.lang.NoSuchMethodError: com.robertx22.world_of_exile.config.FeatureConfig$MyStructureConfig.<init>(III)V
	Mod Version: NONE
	Mod Issue URL: https://change.me.to.your.issue.tracker.example.invalid/
	Exception message: java.lang.NoSuchMethodError: com.robertx22.world_of_exile.config.FeatureConfig$MyStructureConfig.<init>(III)V
Stacktrace:
	at com.robertx22.age_of_exile.dimension.DungeonDimensionJigsaw.<clinit>(DungeonDimensionJigsaw.java:26) ~[?:?] {re:classloading}
	at com.robertx22.age_of_exile.dimension.DimensionInit.init(DimensionInit.java:9) ~[?:?] {re:classloading}
	at com.robertx22.age_of_exile.mmorpg.MMORPG.<init>(MMORPG.java:108) ~[?:?] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[?:36.2] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2639/265625523.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3029/2035065227.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}
****

Here is the full crash report
https://pastebin.com/x6UEzmdX

Here is the latest.log
https://pastebin.com/yUiPu6sZ

Thanks again for your amazing and unique mod.

**Comment by LinJonKur** [comment]
I have the same problem

**Comment by RobertSkalko** [comment]
I forgot to add dependencies to forge config, so they are currently only shown on the curseforge page for the file. Wll be fixed next update
