### ISSUE TITLE
Crash.

### ISSUE THREAD

**Issue by nomadSky** [RobertSkalko/Mine-and-Slash#306]
![image](https://user-images.githubusercontent.com/63458578/139531717-e0a0dd23-c2a4-45d8-852e-7c7d21cebd36.png)

I updated mod today and my game just crashing.

**Comment by nomadSky** [comment]
-- Head --
Thread: Render thread
Stacktrace:
	at com.robertx22.age_of_exile.dimension.DungeonDimensionJigsaw.<clinit>(DungeonDimensionJigsaw.java:26) ~[?:?] {re:classloading}
-- MOD mmorpg --
Details:
	Mod File: Mine_and_Slash_BETA-1.16.5-3.0.1.jar
	Failure message: Age Of Exile (mmorpg) has failed to load correctly
		java.lang.NoSuchMethodError: com.robertx22.world_of_exile.config.FeatureConfig$MyStructureConfig.<init>(III)V
	Mod Version: NONE
	Mod Issue URL: https://change.me.to.your.issue.tracker.example.invalid/
	Exception message: java.lang.NoSuchMethodError: com.robertx22.world_of_exile.config.FeatureConfig$MyStructureConfig.<init>(III)V
Stacktrace:
	at com.robertx22.age_of_exile.dimension.DungeonDimensionJigsaw.<clinit>(DungeonDimensionJigsaw.java:26) ~[?:?] {re:classloading}
	at com.robertx22.age_of_exile.dimension.DimensionInit.init(DimensionInit.java:9) ~[?:?] {re:classloading}
	at com.robertx22.age_of_exile.mmorpg.MMORPG.<init>(MMORPG.java:108) ~[?:?] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[?:36.2] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3017/655053439.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3203/893943977.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

**Comment by RobertSkalko** [comment]
My bad, downgrade the dungeons/world of exile mod till i fix mine and slash

**Comment by nomadSky** [comment]
Thanks, It helped me.
