### ISSUE TITLE
An awful crash occurs in both 1.14.4 and 1.15.2 in mc server

### ISSUE THREAD

**Issue by casketaaa** [RobertSkalko/Mine-and-Slash#353]
I've tried 1.14.4 and 1.15.2.In a totally clean forge server and forge client, with only two mods:ms and curios.I can open the Stats GUI in local world.But while I wants to open Stats GUI in server(offline mode, only with ms and curios),the client crashed,and the server is alive and well.Here is the crash_report:(And sorry about my poor English  if u have any problem in understanding my question.)
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 23-8-9 下午9:18
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at com.robertx22.mine_and_slash.gui.screens.stat_allocation_screen.StatAllocationScreen$IncreaseStatButton.renderToolTip(StatAllocationScreen.java:197) ~[?:1.15.2-3.15.24] {re:classloading}
	at com.robertx22.mine_and_slash.gui.screens.stat_allocation_screen.StatAllocationScreen.lambda$render$1(StatAllocationScreen.java:122) ~[?:1.15.2-3.15.24] {re:classloading}
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_351] {}
	at com.robertx22.mine_and_slash.gui.screens.stat_allocation_screen.StatAllocationScreen.render(StatAllocationScreen.java:122) ~[?:1.15.2-3.15.24] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:480) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:924) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) ~[1.15.2.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_351] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_351] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_351] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_351] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.15.2-31.2.57.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.robertx22.mine_and_slash.gui.screens.stat_allocation_screen.StatAllocationScreen$IncreaseStatButton.renderToolTip(StatAllocationScreen.java:197)
	at com.robertx22.mine_and_slash.gui.screens.stat_allocation_screen.StatAllocationScreen.lambda$render$1(StatAllocationScreen.java:122)
	at java.util.ArrayList.forEach(Unknown Source)
	at com.robertx22.mine_and_slash.gui.screens.stat_allocation_screen.StatAllocationScreen.render(StatAllocationScreen.java:122)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)

-- Screen render details --
Details:
	Screen name: com.robertx22.mine_and_slash.gui.screens.stat_allocation_screen.StatAllocationScreen
	Mouse location: Scaled: (290, 63). Absolute: (1160.000000, 255.000000)
	Screen size: Scaled: (480, 255). Absolute: (1920, 1017). Scale factor of 4.000000

-- Affected level --
Details:
	All players: 2 total; [ClientPlayerEntity['casket'/1301, l='MpServer', x=81.62, y=76.00, z=211.76], RemoteClientPlayerEntity['Stautical'/1299, l='MpServer', x=83.44, y=68.00, z=244.00]]
	Chunk stats: Client Chunk Cache: 729, 462
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 6364754016334322200
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (80,68,241), Chunk: (at 0,4,1 in 5,15; contains blocks 80,0,240 to 95,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 21603 game time, 6164 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:442)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1763)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:567)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_351, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6182595424 bytes (5896 MB) / 7449083904 bytes (7104 MB) up to 7516192768 bytes (7168 MB)
	CPUs: 16
	JVM Flags: 11 total; -Xmx7168m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	ModLauncher: 5.1.2+70+master.2845bb9
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-2.2.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.57.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.57.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.57.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.57.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.57.jar fml TRANSFORMATIONSERVICE 
		/I18nUpdateMod-3.5.0-all.jar I18nUpdateMod TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.57
	FML Language Providers: 
		javafml@31.2
		minecraft@1
		kotlinforforge@1.17.0
	Mod List: 
		forge-1.15.2-31.2.57-client.jar Minecraft {minecraft@1.15.2 DONE}
		JustEnoughCharacters-1.15.2-4.1.2.jar Just Enough Characters {jecharacters@4.1.2 DONE}
		useful_backpacks-1.15.2-1.10.3.77.jar Useful Backpacks {usefulbackpacks@1.10.3.77 DONE}
		libIPN-forge-1.15-1.0.8.jar libIPN {libipn@1.0.8 DONE}
		u_team_core-1.15.2-3.0.2.257.jar U Team Core {uteamcore@3.0.2.257 DONE}
		ironfurnaces-1.15.2-2.0.4.jar Iron Furnaces {ironfurnaces@2.0.4 DONE}
		InventoryProfilesNext-forge-1.15-1.8.6.jar Inventory Profiles Next {inventoryprofilesnext@1.8.6 DONE}
		Mine+and+Slash-1.15.2-3.15.24.jar Mine and Slash {mmorpg@3.15.24 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		jei-1.15.2-6.0.3.15.jar Just Enough Items {jei@6.0.3.15 DONE}
		forge-1.15.2-31.2.57-universal.jar Forge {forge@31.2.57 DONE}
		curios-FORGE-1.15.2-2.0.2.7.jar Curios API {curios@FORGE-1.15.2-2.0.2.7 DONE}
		Waystones_1.15.2-6.0.2.jar Waystones {waystones@6.0.2 DONE}
		WailaHarvestability-mc1.15.2-1.1.12.jar Waila Harvestability {wailaharvestability@1.1.12 DONE}
		journeymap-1.15.2-5.7.0.jar Journeymap {journeymap@5.7.0 DONE}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
		StorageDrawers-1.15.2-7.0.3.jar Storage Drawers {storagedrawers@1.15.2-7.0.3 DONE}
		OreExcavation-1.7.151.jar Ore Excavation {oreexcavation@NONE DONE}
	Launched Version: 1.15.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2 GL version 4.6.0 NVIDIA 536.67, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: file/Minecraft-Mod-Language-Modpack-Converted-1.15.2.zip
	Current Language: 简体中文 (中国)
	CPU: 16x AMD Ryzen 7 5800H with Radeon Graphics

**Comment by casketaaa** [comment]
I know few about java and forge.But from my poor knowledge gained from stm32,the problem occured here:
![image](https://github.com/RobertSkalko/Mine-and-Slash/assets/129755876/d4498ab9-5a4c-463f-9c71-09a6217c51e9)
and I dont know how to fix that

**Comment by casketaaa** [comment]
I know few about java and forge.But from my poor knowledge gained from stm32,the problem occured here:
![image](https://github.com/RobertSkalko/Mine-and-Slash/assets/129755876/d4498ab9-5a4c-463f-9c71-09a6217c51e9)
and I dont know how to fix that

**Comment by casketaaa** [comment]
hmmmmm got it, a stupid problem.cuz the server admin use the wrong file as the server core.
