### ISSUE TITLE
Random game crash 1.14.3

### ISSUE THREAD

**Issue by LustrousBlue** [RobertSkalko/Mine-and-Slash#41]
The game randomly crashes with seemingly different triggers each time, but with the same error message, but with this latest crash I got the crash report, the crash doesn't happen without mine and slash.

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 7/9/19 10:20 AM
Description: Exception ticking world

java.lang.IllegalStateException: TickNextTick list out of synch
	at net.minecraft.world.ServerTickList.func_205365_a(SourceFile:57) ~[?:?] {}
	at net.minecraft.world.ServerWorld.func_72835_b(ServerWorld.java:298) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:813) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:748) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:609) [?:?] {pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.ServerTickList.func_205365_a(SourceFile:57)
	at net.minecraft.world.ServerWorld.func_72835_b(ServerWorld.java:298)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['epicninja532'/111, l='OWO', x=-354.64, y=118.73, z=-120.87]]
	Chunk stats: ServerChunkCache: 3351
	Level dimension: DimensionType{minecraft:overworld}
	Level name: OWO
	Level seed: -3651833984138631357
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (-256,64,176), Chunk: (at 0,4,0 in -16,11; contains blocks -256,0,176 to -241,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 38946 game time, 27131 day time
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 92420 (now: false), thunder time: 2958 (now: true)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:813)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:748)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:609)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.3
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 951664640 bytes (907 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	FML: New FML!
	Loaded coremods (and transformers): Nothing
	Player Count: 1 / 8; [ServerPlayerEntity['epicninja532'/111, l='OWO', x=-354.64, y=118.73, z=-120.87]]
	Data Packs: vanilla, mod:waterstrainer, mod:uteamcore, mod:usefulbackpacks, mod:tombstone, mod:ruins, mod:mmorpg, mod:jei, mod:forge, mod:doggytalents, mod:curios, mod:curioofundying, mod:creeperspider, mod:biomesoplenty
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by LustrousBlue** [comment]
It may be a issue with forge, Ill try some different versions and see if it helps

**Comment by RobertSkalko** [comment]
doesnt seem to be my mod's fault. post more errors (actual log/debug files with the errors) if u still think it's my fault. I don't see any log coming to my mod.

**Comment by LustrousBlue** [comment]
Understood
