### ISSUE TITLE
I always get this crash

### ISSUE THREAD

**Issue by Neobenmike** [RobertSkalko/Mine-and-Slash#43]
I always get this crash everytime I use your mod
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 7/11/19 8:00 PM
Description: Exception ticking world

java.lang.IllegalStateException: Entity is already tracked!
	at net.minecraft.world.chunk.ChunkManager.func_219210_a(ChunkManager.java:875) ~[?:?] {}
	at net.minecraft.world.chunk.ServerChunkProvider.func_217230_c(SourceFile:441) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.world.ServerWorld.func_217465_m(ServerWorld.java:950) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.world.ServerWorld.func_72835_b(ServerWorld.java:350) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:813) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:748) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:609) [?:?] {pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.chunk.ChunkManager.func_219210_a(ChunkManager.java:875)
	at net.minecraft.world.chunk.ServerChunkProvider.func_217230_c(SourceFile:441)
	at net.minecraft.world.ServerWorld.func_217465_m(ServerWorld.java:950)
	at net.minecraft.world.ServerWorld.func_72835_b(ServerWorld.java:350)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['neobenmike'/252, l='Neo Empire', x=74.30, y=81.00, z=-64.41]]
	Chunk stats: ServerChunkCache: 2025
	Level dimension: DimensionType{minecraft:overworld}
	Level name: Neo Empire
	Level seed: 280823388
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (80,74,-48), Chunk: (at 0,4,0 in 5,-3; contains blocks 80,0,-48 to 95,255,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 337982 game time, 171158 day time
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 125293 (now: false), thunder time: 9966 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:813)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:748)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:609)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.3
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2276478600 bytes (2171 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	FML: New FML!
	Loaded coremods (and transformers): Nothing
	Player Count: 1 / 8; [ServerPlayerEntity['neobenmike'/252, l='Neo Empire', x=74.30, y=81.00, z=-64.41]]
	Data Packs: mod:mmorpg, mod:ceilingtorch, vanilla, mod:xaerominimap, mod:waila, mod:uteamcore, mod:usefulbackpacks, mod:torchbandolier, mod:silentlib, mod:scalinghealth, mod:practicaltools, mod:mobcatcher, mod:metalbarrels, mod:jei, mod:inventorysorter, mod:gobber2, mod:funores, mod:forge, mod:findercompass, mod:fastleafdecay, mod:f2l, mod:extrabows, mod:extraanvils, mod:curios, mod:autodropper
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by RobertSkalko** [comment]
you sure you're not using other mods? Like silent gems or other silent mods? I think i saw them causing this crash.

**Comment by Neobenmike** [comment]
Will do that, I will report again if it still occurs. 
Another question, is this incompatible with silent mods?

**Comment by RobertSkalko** [comment]
Shouldn't be. I think it's just their problem.

**Comment by ProsperCraft** [comment]
This crash was silent gear, we reported it to him and he fixed it in the most recent update, you can close this issue.

**Comment by Neobenmike** [comment]
Great thanks :D
