### ISSUE TITLE
[1.14.4] java.lang.NoSuchMethodError: net.minecraft.util.text.TextFormatting.func_211163_e()Ljava/lang/Integer;

### ISSUE THREAD

**Issue by pandory-network** [RobertSkalko/Mine-and-Slash#85]
**Mine and Slash Version:** Mine and Slash-1.14.4-2.8.3
**Forge Version:** 1.14.4-28.1.10

**Error:**
```
Time: 9/22/19 12:31 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.util.text.TextFormatting.func_211163_e()Ljava/lang/Integer;
	at com.robertx22.mine_and_slash.uncommon.datasaving.Gear.colorItem(Gear.java:48) ~[?:1.14.4-2.8.3] {}
	at com.robertx22.mine_and_slash.uncommon.datasaving.Gear.Save(Gear.java:39) ~[?:1.14.4-2.8.3] {}
	at com.robertx22.mine_and_slash.loot.gens.GearLootGen.CreateStack(GearLootGen.java:138) ~[?:1.14.4-2.8.3] {}
	at com.robertx22.mine_and_slash.loot.gens.GearLootGen.generateOne(GearLootGen.java:40) ~[?:1.14.4-2.8.3] {}
	at com.robertx22.mine_and_slash.loot.gens.BaseLootGen.tryGenerate(BaseLootGen.java:33) ~[?:1.14.4-2.8.3] {}
	at com.robertx22.mine_and_slash.loot.MasterLootGen.populateOnce(MasterLootGen.java:59) ~[?:1.14.4-2.8.3] {}
	at com.robertx22.mine_and_slash.loot.MasterLootGen.generateLoot(MasterLootGen.java:22) ~[?:1.14.4-2.8.3] {}
	at com.robertx22.mine_and_slash.loot.MasterLootGen.generateLoot(MasterLootGen.java:78) ~[?:1.14.4-2.8.3] {}
	at com.robertx22.mine_and_slash.loot.MasterLootGen.genAndDrop(MasterLootGen.java:86) ~[?:1.14.4-2.8.3] {}
	at com.robertx22.mine_and_slash.onevent.entity.OnMobDeathDrops.mobOnDeathDrop(OnMobDeathDrops.java:57) ~[?:1.14.4-2.8.3] {}
	at net.minecraftforge.eventbus.ASMEventHandler_28_OnMobDeathDrops_mobOnDeathDrop_LivingDeathEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:346) ~[?:?] {}
	at net.minecraft.entity.LivingEntity.func_70645_a(LivingEntity.java:1096) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:973) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.monster.MonsterEntity.func_70097_a(SourceFile:72) ~[?:?] {}
	at net.minecraft.entity.player.PlayerEntity.func_71059_n(PlayerEntity.java:1059) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71059_n(ServerPlayerEntity.java:1219) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147340_a(ServerPlayNetHandler.java:1075) ~[?:?] {}
	at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:69) ~[?:?] {}
	at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:13) ~[?:?] {}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:699) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:679) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:626) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222] {}
```

**Logs:**
[crash-2019-09-22_12.34.36-server.txt](https://github.com/RobertSkalko/Mine-and-Slash/files/3639621/crash-2019-09-22_12.34.36-server.txt)
[debug-3.log](https://github.com/RobertSkalko/Mine-and-Slash/files/3639622/debug-3.log)
[2019-09-22-3.log](https://github.com/RobertSkalko/Mine-and-Slash/files/3639623/2019-09-22-3.log)

**Comment by RobertSkalko** [comment]
sorry again, pushing another update

**Comment by pandory-network** [comment]
No Problem, Bugs are there, to be found xD

**Comment by pandory-network** [comment]
Bug is fixed. Thx
